### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by KiwiHawk** [ickputzdirwech/SeaBlockCustomPack#1]
- [x] Broken links in README.md :  Sea Block Pack, Explosive Excavation, Landfill Painting
- [x] _Enable pressure fluid tanks_ setting does have an effect. It controls if the [Jax 35 pressure tanks](https://forums.factorio.com/viewtopic.php?p=396869#p396869) are available.
- [x] _Hid startup settings regarding "Starting resources" from mod "Angel's Refining"._ DONE KiwiHawk/SeaBlock#49
- [x] _Add conversion recipes_ default has been changed to false. I'm not hiding it as it it may useful to someone if they are adding extra mods. I've logged a bug with Angel's that setting do false only hides the recipes, not the valve itself. KiwiHawk/SeaBlock#18
- [x] _Hid startup settings "Enable water ores" and "infinite ores"_ DONE KiwiHawk/SeaBlock#49
- [x] _Burner and fluid powered heat sources_ setting does have an effect. It controls if the heat sources are available. While more expensive than a fluid boiler, they are more efficient as they have a 12.5% (set by Sea Block) neighbour bonus.
- [x] _Burner power phase_ DONE KiwiHawk/SeaBlock#48
- [x] Have changed default for _Science pack colors update_ to false. It has an effect if SCT is not enabled. SCT dev said they will make a change to respect the setting. KiwiHawk/SeaBlock#36
- [x] _Warehouses and logistic warehouses are dependent on silos and logistic silos._ I already see this in my tech tree?
- [x] _Raw gem recipes_ DONE KiwiHawk/SeaBlock#61
- [x] _Technologies (WIP): crushing / smelting_ DONE KiwiHawk/SeaBlock#3
- [x] _Alien artifact recipes_ DONE KiwiHawk/SeaBlock#5
- [x] _Renamed carbon dioxide recipes_ Remove carbon dioxide from carbon recipe. DONE
- [x] _Items, recipes, entities and technologies got hidden where necessary. Redundant technology unlocks got removed._ I'll look into this later.
- [x] _Hid accumulator._ Some people do use solar panels + accumulators. Plus they can be useful for wiring to a speaker to detect when you're low on power generation.
- [x] _Hid burner and fluid burning heat sources._ As noted earlier, these are the best way of burning fuel.
- [x] _Hid XYZ from GUIs._ Do you remember which GUIs? I'd like to check this.

Reordering looks good from your mod screenshots.

**Comment by KiwiHawk** [comment]
I've been working on a furnace rework; not yet released KiwiHawk/SeaBlock#28.

Bob's chemical furnaces have been completely removed.
Metal mixing specific recipes have been moved to a different machine.

I thought about removing the metal mixing furnaces too but it can be useful or some people just prefer being able to set the recipe on a furnace. So there are 10 furnaces left (12 if fluid burning furnaces are enabled). 5 tiers, each with a furnace type and an assembly machine type (where you set the recipe). The multi-purpose furnaces are the top two tiers for the assembly machine type furnaces.

I'd like to rename the metal mixing and multi-purpose furnaces but not sure what to rename them too. Any suggestions?

I'm considering adding a new setting to show/hide both the the metal mixing and multi-purpose furnaces. Until then, I'm keeping the multi-purpose furnaces available. Else the assembly machine type furnaces are missing the top two tiers.

**Comment by KiwiHawk** [comment]
Hiding settings can be problematic. Overwriting the default setting is fine for a clean new install. But if someone already had that mod the setting could already be something different and they then have no way of changing it. If you are going to hide settings, you really should be overwriting the values too, not just the defaults. This is the entire purpose of A Sea Block Config mod.

Multiple mod developers have requested a better way of overwriting settings from another mod. No luck yet but hopefully they will add a better way! It's actually only an issue for bool settings as all others can be forced by setting the allowed values.

**Comment by ickputzdirwech** [comment]
Hey thanks for all the feedback, I really appreciate it! Glad to hear that you are already working on a lot of the stuff. I'll answer everything I feel like I should, point by point:

> * Broken links in README.md :  Sea Block Pack, Explosive Excavation, Landfill Painting

Oups, thanks for letting me know, fixed it for the next version., forgot the "https://". I'm a bit embarrassed that of all things your mods were effected.

> * _Enable pressure fluid tanks_ setting does have an effect. It controls if the [Jax 35 pressure tanks](https://forums.factorio.com/viewtopic.php?p=396869#p396869) are available.

I intended to hide the pressure tank. I think the storage tanks from bob's are more in line with the mod pack and as a compensation I increased their size. In the next version I'll also double the size of the small storage tanks. I removed the wrong notice in the readme. Thanks for pointing it out.

> * _Add conversion recipes_ default has been changed to false. I'm not hiding it as it it may useful to someone if they are adding extra mods.

Makes sense if you want to account for possible other mods. Think I'll leave it the way I did it.

> * _Burner and fluid powered heat sources_ setting does have an effect. It controls if the heat sources are available. While more expensive than a fluid boiler, they are more efficient as they have a 12.5% (set by Sea Block) neighbour bonus.

Again, I intended to hide them. I think I just copied the sentence, changed the keywords and forgot to remove the "does nothing" notice. I honestly didn't realise that they are more efficient than boilers, but just hid them, in an attempt to streamline the power option (if you want to use heat exchangers, go nuclear) and because the burner heat sources are just plain ugly imo.

> * Have changed default for _Science pack colors update_ to false. It has an effect if SCT is not enabled. SCT dev said they will make a change to respect the setting.

Good to know. As I said I only accounted for the default mod list.

> * _Warehouses and logistic warehouses are dependent on silos and logistic silos._ I already see this in my tech tree?

I don't. Maybe my formulation is unclear: Warehouses is now dependent on silos. Logistic warehouses is dependent on logistic silos.

> * Technologies (WIP): crushing / smelting

I had really trouble doing this. I ended up disabling the recipes on_configuration_changed. Maybe it was just me doing something wrong, but it didn't work neither in data-final-fixes nor migrations.

> * _Renamed carbon dioxide recipes_ The carbon dioxide from carbon recipe is being removed. Bob added it. Angel has removed it.

Good to hear. It was worse than the recipe from charcoal anyway. There are still two carbon dioxide recipes though:  one from wood pellets and the one from charcoal. I forgot to mention in the readme that i changed all three of them (it's correct in the changelog).

> * _Hid accumulator._ Some people do use solar panels + accumulators. Plus they can be useful for wiring to a speaker to detect when you're low on power generation.

I only hid the vanilla accumulator. People should use the variants from bob's. The vanilla solar panel is already hidden.

> * _Hid XYZ from GUIs._ Do you remember which GUIs? I'd like to check this.

Bob's electrolyser was visible in the "made in" tooltip. Mining drills and pumpjacks were visible in the bonus gui. Pollution modules and lithia water were visible in the items gui (modules and water treatment tabs). Mining recipes are visible in FNEI and Factory Planner.

> I thought about removing the metal mixing furnaces too but it can be useful or some people just prefer being able to set the recipe on a furnace.

Sure this can be helpful, but imo only in the very beginning. As soon as you have filter inserters (they are available before metal mixing furnaces) this is not really needed. Adding an option to enable them again is a good compromise.

> I'd like to rename the metal mixing and multi-purpose furnaces but not sure what to rename them too. Any suggestions?

Maybe just "Recipe furnace"? Maybe not very eloquent, but it should convey what they are there for.

> Hiding settings can be problematic. Overwriting the default setting is fine for a clean new install. But if someone already had that mod the setting could already be something different and they then have no way of changing it. If you are going to hide settings, you really should be overwriting the values too, not just the defaults. [...] It's actually only an issue for bool settings as all others can be forced by setting the allowed values.

I noticed this issue as well. I'll try changing the value at least for the string and int settings I touched. I also noticed that it's possible to get around this issue by using the "reset X options to default" in the top right corner of the mod settings menu. If the button is not available just change any setting temporarily and then click the button. Hidden settings will be reset as well.

> Reordering looks good from your mod screenshots.

That was pretty much the main reason why I started this mod. Some things are just all all over the place. Not everything I changed is on the screenshots, but most of it (notice that I also changed the order and icons of some groups).

**Comment by ickputzdirwech** [comment]
> > * _Hid XYZ from GUIs._ Do you remember which GUIs? I'd like to check this.
> 
> Bob's electrolyser was visible in the "made in" tooltip. Mining drills and pumpjacks were visible in the bonus gui. Pollution modules and lithia water were visible in the items gui (modules and water treatment tabs). Mining recipes are visible in FNEI and Factory Planner.

I should probably add that I am testing in sandbox mode. So some of the mentioned things might never show up in freeplay. I figured it was worth the effort to properly hide them anyway. In case anyone wants to make blueprints in sandbox or something like that.

**Comment by KiwiHawk** [comment]
> 
> > * Technologies (WIP): crushing / smelting
> 
> I had really trouble doing this. I ended up disabling the recipes on_configuration_changed. Maybe it was just me doing something wrong, but it didn't work neither in data-final-fixes nor migrations.
> 

I've just finished these changes. Have a look at KiwiHawk/SeaBlock#3 for the full list. I've changed more than you did I think. All done in data-updates. I expect to be putting out a new release in the next few days.

**Comment by KiwiHawk** [comment]
> TODO
> TECHNOLOGY DEPENDENCIES
> Alloy processing

DONE KiwiHawk/SeaBlock#50

**Comment by KiwiHawk** [comment]
I've released an updated version of Sea Block. So you could remove the stuff I've done from your mod. Particularly the smelting changes. I've still got a few still marked as TODO. These will go into the next version. Mainly hiding things

**Comment by ickputzdirwech** [comment]
Yeah, I saw it in the mod portal already ;) I just updated my mod too. Timing was perfectly as I were just finishing hiding lots of military stuff.  :) I saw you are working on this as well and you're even planning to remove all alien science (KiwiHawk/SeaBlock/issues/4). Really nice 👍 

PS: While writing this I noticed that I forgot to remove all changes I did regarding the furnaces. Well, next version... Probably won't bother anyone but me anyway

**Comment by KiwiHawk** [comment]
They finally did it! 😁
https://forums.factorio.com/88927
Now for settings you are hiding, don't set the default value. Instead for bool values, set forced_value. For other setting types, set allowed_values.

**Comment by ickputzdirwech** [comment]
> They finally did it!

🥳 💯 🎉

**Comment by KiwiHawk** [comment]
You might want to add an optional dependency on https://mods.factorio.com/mod/reskins-compatibility
Makes all the boards look correct!

**Comment by ickputzdirwech** [comment]
Yeah did that already. I am currently working locally on the next version. I still have to go through some of the changes you made in your latest update and I am making some other small changes as well.

**Comment by Pezzawinkle** [comment]
> Hid XYZ from GUIs. Do you remember which GUIs? I'd like to check this.

The main one that we all seem to forget is the bonuses GUI, labs, damage/speed bonuses... entities which get hidden need to also be removed from this GUI... I cannot remember if I updated angels Lib to do this automatically or not.

**Comment by KiwiHawk** [comment]
I'm hoping to have an updated version of Sea Block out soon, for if you want to start testing. There's been loads of changes! Some off the top of my head that will affect you:
- Most military stuff has been hidden
- Walls are required for biter refugiums
- Recipe Carbon dioxide from wood pellets has been disabled

I believe I have hidden things hidden correct from the bonuses gui etc. If you find stuff that should be hidden but isn't, please let me know!

**Comment by ickputzdirwech** [comment]
Thanks for the heads up! I have been following your changes on GitHub a bit and I really appreciate the work you have done. I guess I'll have to remove quite a lot of stuff from my mod - which is a good thing :)
